メニューの追加
1-system-group/Diary-Sample-Android pull request #5
Opened 2021-11-28 07:29 UTC by birdsea

# 内容
アプリのメニューを追加しました。
![スクリーンショット 2021-11-28 161321](https://user-images.githubusercontent.com/15532048/143733323-4f1358c4-01f3-4013-abef-28900ddee66f.png)

各メニュー、アカウントなど、どうするかはまだ設計していないので、見た目の部分だけです。

# 詳細
- [Material Icon](https://developer.android.com/reference/kotlin/androidx/compose/material/icons/Icons)をライブラリに追加しました。
- 各メニューを選択した際に将来的に画面遷移をすることになりそうなので、使ってはいないですが[Navigation](https://developer.android.com/jetpack/androidx/releases/navigation?hl=ja)もライブラリに追加してます。

2022-07-03 04:58 UTC, abe3333 commented on app/src/main/kotlin/jp/one_system_group/diary_sample_android/ui/menu/DrawerScreen.kt
> +            DrawerItem(item = item, selected = currentRoute == item.route, onItemClick = {
以下、必須ではないですが…。
selectedが、3番目（設定の項目）がtrueになるようになっていますが、
一律でfalse（デフォルトではどこも選択されていない状態）でもいいのではと思いました。

2022-07-03 05:04 UTC, abe3333 requested changes
遅くなってすみません。レビューしました。
1点だけ指摘があるので、確認をお願いいたします。
対応必須ではないと思うので、対応不要でしたらその旨返していただければ、
レビュー完了に持っていきます。

ちなみに流れとしては、このプルリクがマージされた状態のものに、
こちらの画面遷移の対応を入れていこうと思っています。

2022-07-09 10:11 UTC, birdsea commented on app/src/main/kotlin/jp/one_system_group/diary_sample_android/ui/menu/DrawerScreen.kt
> +            DrawerItem(item = item, selected = currentRoute == item.route, onItemClick = {
何か使えるかなと試してみた感じなので、確かに選択されていない状態のほうが良さそうです。
修正しました。
https://github.com/1-system-group/Diary-Sample-Android/pull/5/commits/392afbc5814ce96feaeb782659588849ad8f382f

2022-07-14 10:08 UTC, abe3333 approved these changes
修正確認しました。ありがとうございました。

2022-07-14 10:54 UTC, merged